# Generated by Django 6.0.6 on 2026-06-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Example: 01', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('challenges', models.TextField(help_text='One item per line.')),
                ('actions', models.TextField(help_text='One item per line.')),
                ('outcomes', models.TextField(help_text='One item per line.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(help_text='Example: Sep 2023 — May 2026', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('bullets', models.TextField(blank=True, help_text='One bullet point per line.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💬', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='CJR', max_length=50)),
                ('site_title', models.CharField(default='CJ Regasa — Virtual Assistant Portfolio', max_length=200)),
                ('meta_description', models.TextField(default='Virtual Assistant, Customer Support Specialist, Shopify & E-commerce VA based in the Philippines.')),
                ('availability_badge', models.CharField(default='Available for Full-Time VA, Customer Support, Shopify & E-commerce Roles', max_length=300)),
                ('hero_tag', models.CharField(default='Philippines · Remote · GMT+8', max_length=200)),
                ('hero_name_line1', models.CharField(default='Celito John', max_length=100)),
                ('hero_name_line2', models.CharField(default='Regasa.', max_length=100)),
                ('hero_role', models.CharField(default='Virtual Assistant | Customer Support Specialist | Shopify & E-commerce VA', max_length=300)),
                ('hero_subtitle', models.TextField(default='Helping businesses streamline operations, deliver excellent customer service, and grow their online presence through reliable virtual assistance, e-commerce support, and social media management.')),
                ('hero_initials', models.CharField(default='CJ', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('brands_label', models.CharField(default="Brands & Companies I've Worked With", max_length=200)),
                ('about_section_tag', models.CharField(default='About Me', max_length=100)),
                ('about_title', models.CharField(default='Your Reliable Remote Partner.', max_length=200)),
                ('about_bio_1', models.TextField(blank=True)),
                ('about_bio_2', models.TextField(blank=True)),
                ('about_bio_3', models.TextField(blank=True)),
                ('education_icon', models.CharField(default='🎓', max_length=10)),
                ('education_title', models.CharField(default='BSEd English · Batch 2020', max_length=200)),
                ('education_subtitle', models.CharField(default='Tarlac State University', max_length=200)),
                ('services_section_tag', models.CharField(default='What I Do', max_length=100)),
                ('services_title', models.CharField(default='Services Offered.', max_length=200)),
                ('services_subtitle', models.TextField(default='From customer support to e-commerce and social media — I help businesses run smoother and grow online.')),
                ('experience_section_tag', models.CharField(default='Career Timeline', max_length=100)),
                ('experience_title', models.CharField(default='Professional Experience.', max_length=200)),
                ('experience_subtitle', models.TextField(default='7+ years across BPO, e-commerce, social media, and team training.')),
                ('testimonials_section_tag', models.CharField(default='Kind Words', max_length=100)),
                ('testimonials_title', models.CharField(default='What Clients Say.', max_length=200)),
                ('case_studies_section_tag', models.CharField(default='Real Work, Real Results', max_length=100)),
                ('case_studies_title', models.CharField(default='Case Studies.', max_length=200)),
                ('case_studies_subtitle', models.TextField(default='Detailed breakdowns of challenges, actions, and outcomes from real projects.')),
                ('tools_section_tag', models.CharField(default='Tech Stack', max_length=100)),
                ('tools_title', models.CharField(default='Tools & Platforms.', max_length=200)),
                ('tools_subtitle', models.TextField(default='The platforms and software I use daily to deliver results.')),
                ('contact_section_tag', models.CharField(default='Get In Touch', max_length=100)),
                ('contact_title', models.CharField(default='Ready to Work Together?', max_length=200)),
                ('contact_subtitle', models.TextField(default="Send me a message and I'll get back to you within 24 hours. I'm open to full-time, part-time, and project-based remote roles.")),
                ('email', models.EmailField(default='celitojohn@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+63 981 717 4999', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/cj-regasa')),
                ('linkedin_label', models.CharField(default='LinkedIn — CJ Regasa', max_length=100)),
                ('toast_message', models.CharField(default="Message sent! I'll get back to you within 24 hours.", max_length=200)),
                ('footer_line1', models.CharField(default="© 2026 Celito John Regasa · O'Donnell, Capas, Tarlac, Philippines", max_length=300)),
                ('footer_line2', models.CharField(default='Available for new projects · Philippines (GMT+8)', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='SkillChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: Shopify ✓', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Chip',
                'verbose_name_plural': 'Skill Chips',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Example: 7+', max_length=20)),
                ('label', models.CharField(help_text='Example: Years Experience', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=200)),
                ('author_initial', models.CharField(help_text='Single letter for avatar', max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: CRM & Support', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='portfolio.toolcategory')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['order'],
            },
        ),
    ]
