# Generated by Django 6.0.6 on 2026-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_siteprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Shopify Foundations Certificate', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='Example: Shopify, Coursera, TESDA', max_length=200)),
                ('date_earned', models.CharField(blank=True, help_text='Example: March 2024', max_length=50)),
                ('image', models.FileField(help_text='Upload a photo or scan of your certificate.', upload_to='certificates/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='certificates_section_tag',
            field=models.CharField(default='Credentials', max_length=100),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='certificates_subtitle',
            field=models.TextField(default='Professional certifications and completed training programs.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='certificates_title',
            field=models.CharField(default='Certificates & Training.', max_length=200),
        ),
    ]
